### ISSUE TITLE
Not allowed to load local resource.

### ISSUE THREAD

**Issue by EricEisaman** [leo/electron-next#1]
First of all, thank you for your efforts.  I had success when following your recent article until [taking it to production](https://leo.im/2017/electron-next#making-the-dream-come-true). 

My resulting distribution had no window content.  I enabled developer tools and found this error: 
![electron-next-error](https://user-images.githubusercontent.com/6116865/28281283-8cec769a-6af4-11e7-8fe8-534a3368cf52.png)

I have made a repo for my test of electron-next. [Here](https://github.com/EricEisaman/electron-next-test/issues/1) is the issue on my repo.

**Comment by leo** [comment]
[This](https://github.com/EricEisaman/electron-next-test/blob/e5b014813f3ab28174fd1731313bd87a94c45758/package.json#L14-L19) property needs to be a sub property of `build`.

> First of all, thank you for your efforts

😊 🙏

**Comment by EricEisaman** [comment]
Thanks Leo. 🙏

**Comment by EricEisaman** [comment]
The article shows this:

"build": {
  "asar": false
},"extraResources": [
  {
    "from": "renderer/out",
    "to": "app/renderer"
  }
]

Should it instead be:

"build": {
"asar": false,
"extraResources": [
{
"from": "renderer/out",
"to": "app/renderer"
}
]
},

**Comment by leo** [comment]
Fixed! Thanks 😊

**Comment by EricEisaman** [comment]
A link to the finished source code at the bottom the article, https://leo.im/2017/electron-next , would be very helpful.

**Comment by leo** [comment]
It's linked [here](https://leo.im/2017/electron-next#highlighted-oss-projects)!

**Comment by EricEisaman** [comment]
I just found the link to the last part of the article. I was suggesting
putting a link to a zipped archive of the final source code.

**Comment by leo** [comment]
You can download the repo as a ZIP file by clicking „Download“ on the repo 😊

**Comment by EricEisaman** [comment]
Which repo?  I am not looking for the electron-next repo, but specifically
for a repo covering the exact example you walk through in the article.
Pardon my ignorance, but I can't seem to find a link to the exact code you
cover in the article. I am in the process of preparing a learning unit for
some high school students to follow this school year. I greatly appreciate
your assistance.

Sincerely,
Eric

**Comment by EricEisaman** [comment]
Found it!! Sorry!!🙏

**Comment by leo** [comment]
Sweet! No problem 😊 Let me know if you need anything else.
