### ISSUE TITLE
Authentication Tokens in electron-next

### ISSUE THREAD

**Issue by alexpareto** [leo/electron-next#11]
Generally in next.js it's best practice to store authentication tokens in cookies so that the token can be read in both the server and client for SSR (e.g. in getInitialProps). Since electron doesn't support cookies in the renderer process - what would be the best way to keep track of auth tokens (and persist them between sessions)?

In now-desktop, it seems like a [config](https://github.com/zeit/now-desktop/blob/be0add76aed5e27a19bbed99f0eb5490ef32a8b6/main/utils/config.js) in the main process is used and then electron remote is used to communicate with the config. Is there a more simple best practice than this?

**Comment by leo** [comment]
Two things:

- The main process is the best way to store data
- [electron-store](https://www.npmjs.com/package/electron-store) is the best abstraction for that 

😊
