### ISSUE TITLE
Run renderer-specific code?

### ISSUE THREAD

**Issue by adamkirkwood** [leo/electron-next#12]
How might I be able to run renderer-specific code, similar to https://github.com/ourcodeworld/electron-examples/blob/master/examples/electron-folderandfilewatcher/index.html ?

**Comment by leo** [comment]
Check for the existence of `window` or do it like [this](https://github.com/zeit/now-desktop/blob/9e2c82b1946785d98df2f9aa2e7301f248fc0235/renderer/components/feed/search.js#L108-L112) 😊
