### ISSUE TITLE
Next@6 breaks dist build

### ISSUE THREAD

**Issue by zawupf** [leo/electron-next#17]
In a dist build the `main.js` file cannot be loaded.

Next@6 creates the `main.js` file under `_next/static/commons`. Therefore the file protocol interception path replacement matches twice, resulting in an invalid path to `main.js`.

A `break` after the first match fixes the issue for me: https://github.com/zawupf/electron-next/commit/d92fd0e36d9241a229c217f9d980c4f5fbbcbbea

**Comment by Guizzu** [comment]
Any idea on when can we get this fixed?
