### ISSUE TITLE
Electron app freezes quickly after launching on Ubuntu 18.04

### ISSUE THREAD

**Issue by Klooven** [leo/electron-next#18]
I recently upgraded from Ubuntu 16.04 to Ubuntu 18.04 (fresh install), and after this my app freezes shortly after launching it for some reason when running through `npm start`.

- The app is based on the [electron-next skeleton](https://github.com/leo/electron-next-skeleton)
- It is using Electron 2.0.0
- Running `ELECTRON_ENABLE_LOGGING=true npm start` didn't give any special messages

I noticed that if I run the program with the VS Code debugger, _that seemed to run the app without electron-next (pages didn't get built)_, everything worked correctly and the app didn't freeze. That's why I believe the problem is on electron-next's side.

Please tell me if you need more information.

Here for reference the important parts of my `package.json`:

```json
{
  "name": "app",
  "version": "2.0.0",
  "description": "app",
  "main": "main/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron .",
    "build": "next build renderer && next export renderer",
    "dist": "npm run build && echo \"Generate setup\""
  },
  "devDependencies": {
    "axios": "~0.18.0",
    "electron": "^2.0.0",
    "next": "^6.0.2",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-form": "^3.5.5"
  },
  "dependencies": {
    "app-root-path": "^2.0.1",
    "electron-is-dev": "^0.3.0",
    "electron-next": "^3.1.4"
  }
}
```

**Comment by Klooven** [comment]
After more investigation, I think the problem is in Electron.

**Comment by jfrux** [comment]
I'm also experiencing this...
It only happens for me when I'm running my dev renderer though...

Any tips?

**Comment by Klooven** [comment]
@jfrux You may find good tips in electron/electron#12850
