### ISSUE TITLE
Error: "Can't resolve 'fs'"

### ISSUE THREAD

**Issue by trevordmiller** [leo/electron-next#2]
I'm getting this error when using https://github.com/leo/electron-next-skeleton

![image](https://user-images.githubusercontent.com/5497885/28748402-2d128d7a-7474-11e7-9411-9ed9c80bc087.png)

Should the skeleton `next.config.js` have a `target` of `electron-renderer`?

Here is my repo: https://github.com/trevordmiller/hideaway. Can be reproduced by cloning and running `npm install && npm run dev`.

**Comment by trevordmiller** [comment]
Looks like that is what is being done in now-desktop: https://github.com/zeit/now-desktop/blob/master/renderer/next.config.js#L3. I made the change and it is working: https://github.com/trevordmiller/hideaway/commit/979b91544380c27d02caa59222c548a66abd84cd. Would be helpful to update https://github.com/leo/electron-next-skeleton to work out of the box; I tried to put this issue there but that repo doesn't allow issues.

**Comment by riddla** [comment]
@trevordmiller: I hit this error, too. Do you think it would make (more) sense to update https://github.com/zeit/next.js/blob/master/examples/with-electron/renderer/next.config.js?
