### ISSUE TITLE
Potential bug with .next/BUILD_ID

### ISSUE THREAD

**Issue by trevordmiller** [leo/electron-next#3]
Hey @leo, thank you for your efforts to make building Electron apps with Next.js simpler! I've followed along with the [blog post](https://leo.im/2017/electron-next) and skeleton app and have everything working locally, but when I run `next build renderer && next export renderer` as instructed, I get this error: `no such file or directory, open '{myAppDir}/renderer/.next/BUILD_ID'`:

<img width="1440" alt="screen shot 2017-07-30 at 12 59 28 am" src="https://user-images.githubusercontent.com/5497885/28751374-e4da8e1e-74c2-11e7-934c-4f2a606e7a23.png">

Is this a bug with how `electron-next` exports? I'm using this `next.config.js`:
<img width="479" alt="screen shot 2017-07-30 at 1 00 03 am" src="https://user-images.githubusercontent.com/5497885/28751383-1292621e-74c3-11e7-94f7-37ec4ff6921c.png">

Here is my project: https://github.com/trevordmiller/hideaway. This issue can be reproduced by cloning it and running `npm install && npm run build`

**Comment by leo** [comment]
Fixed on Slack. Just upgrade to `next@3.0.1-beta.20` 😊
