### ISSUE TITLE
electron-builder config file

### ISSUE THREAD

**Issue by develar** [leo/electron-next#5]
I suppose you are not aware that you can provide config file for electron-builder :)

Please see how is it implemented in electron-webpack:

* file https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/electron-builder.yml included into the module
* user can use it as `"extends": "electron-webpack/electron-builder.yml"` 

But actually electron-builder detects electron-webpack and automatically set `extends`. If you will add such base electron-builder file, I can support `electron-next` to automatically set extends in the same way.

**Comment by leo** [comment]
Sweet! Is it possible to use JSON for that?

**Comment by develar** [comment]
Yes, JSON, JSON5 and TOML are also supported (https://github.com/electron-userland/electron-builder/wiki/Options).

**Comment by leo** [comment]
Wonderful, thanks!

**Comment by leo** [comment]
Thanks again for the suggestion! But since we only have files in the config that need to be customized by the user (depending on his directory names), we shouldn't introduce a default config.
