### ISSUE TITLE
using electron associated modules that can't be renderered in the server

### ISSUE THREAD

**Issue by walleXD** [leo/electron-next#8]
HI,

I am trying to use the electron redux module which allows communication between the main and renderer thread using redux but it breaks because next tries to ssr it all other redux middlewares. Any idea on the best way to approach this? 

I know next.js doesn't allow us the option to disable ssr and I tried to use React noSSR module but I couldn't get it to work too

So, what would be the best way to approach this?

**Comment by leo** [comment]
Check for the existence `document` or `window` (which is only available in the renderer).
