### ISSUE TITLE
Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by joseshiru** [leo/electron-next#9]
Hi,

First I have to say thanks for the plugin.

I'm creating an app by using your example. 
I need to store some files in \AppData\Local\ by using the app.getPath() function from electron.

However, after running the code, the file is created but the browser shows an error saying: "An unexpected error has occurred." and the console says: Cannot read property 'getPath' of undefined

Do I'm doing something wrong?

Thanks

**Comment by leo** [comment]
The same problem as [here](https://github.com/leo/electron-next-skeleton/issues/3) and [here](https://github.com/leo/electron-next/issues/8)... 😊

**Comment by joseshiru** [comment]
God bless you 😊
